"""
Generate the §1.7 grade-review fixture set (PR-G1(e)).

The seam between backend and frontend is not the prose in the spec — it is this
fixture set plus the named tests. So these files are GENERATED by real code
paths and regenerated when shapes change; they are never hand-written, and the
diff is reviewed.

    python scripts/gen_grade_review_fixtures.py --from-run <results_dir>
    python scripts/gen_grade_review_fixtures.py --check      # regenerate + diff

`--from-run` reads real `GradedTestDraft` JSON produced by the eval runner under
the ratified pin (R-9 condition i: generated with the flag ON). It does not call
a provider itself: grading is the eval runner's job, and a fixture generator
that could spend money is a fixture generator someone runs by accident.

WHAT THIS EMITS TODAY (PR-G1) vs WHAT WAITS:
  * draft_<student>.json      — real drafts, now carrying checks[]
  * pricing_vectors.json      — the AI-only vectors: (draft, {}) -> effective
  * MANIFEST.json             — what is present, what is pending, and why
  * overlay_examples.json and the overlay half of pricing_vectors NEED the
    PR-G5 overlay model (verdict-level overrides) and are emitted then. The
    manifest says so explicitly rather than shipping empty files that look done.
  * batch_feed_*.json         — PR-G8 (the batch feed shape does not exist yet).
  * audit_deltas_example.json — STRUCK by ruling R-1; the audit is deferred.
"""
from __future__ import annotations

import argparse
import json
import sys
from decimal import Decimal
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

OUT = BACKEND / "tests" / "fixtures" / "grade_review"
STUDENTS = ("dan_basiuk", "din_ezra", "moran_aharon", "omer_gelber", "yonatan_basiuk")


def _load_drafts(run_dir: Path) -> dict:
    """One draft per student — the FIRST repeat, so the set is deterministic."""
    drafts = {}
    for student in STUDENTS:
        for cand in sorted((run_dir / "drafts").glob(f"{student}_r*.json")):
            if cand.name.endswith(".meta.json"):
                continue
            drafts[student] = json.loads(cand.read_text(encoding="utf-8"))
            break
    missing = [s for s in STUDENTS if s not in drafts]
    if missing:
        raise SystemExit(f"run {run_dir.name} has no draft for: {missing}")
    return drafts


def _coverage(drafts: dict) -> dict:
    """§1.7 requires the set to CONTAIN certain shapes. Report them rather than
    assume: a fixture set that silently lost its not_found quote stops testing
    the thing it exists to test."""
    seen = {"not_found": [], "fuzzy": [], "skipped_no_answer": [], "failed_scope": [],
            "terminals_with_checks": 0, "terminals_without_checks": 0}
    for student, d in drafts.items():
        for scope in d.get("scope_outcomes") or []:
            if scope.get("graded_by") == "skipped_no_answer":
                seen["skipped_no_answer"].append(f"{student}:{scope.get('question_id')}")
            if scope.get("graded_by") == "failed":
                seen["failed_scope"].append(f"{student}:{scope.get('question_id')}")
            for crit in scope.get("criterion_outcomes") or []:
                for leaf in (crit.get("sub_criterion_outcomes") or [crit]):
                    checks = leaf.get("checks")
                    seen["terminals_with_checks" if checks else
                         "terminals_without_checks"] += 1
                    for c in checks or []:
                        if c.get("quote_status") == "not_found":
                            seen["not_found"].append(c["check_id"])
                        elif c.get("quote_status") == "fuzzy":
                            seen["fuzzy"].append(c["check_id"])
    return seen


def _pricing_vectors(drafts: dict) -> list:
    """(draft, overlay) -> effective points. Today the overlay is empty: the
    verdict-level overlay is PR-G5. These AI-only vectors are what the frontend
    mirror must reproduce byte-for-byte first."""
    vectors = []
    for student, d in drafts.items():
        for scope in d.get("scope_outcomes") or []:
            for crit in scope.get("criterion_outcomes") or []:
                for leaf in (crit.get("sub_criterion_outcomes") or [crit]):
                    tid = leaf.get("sub_criterion_id") or leaf.get("criterion_id")
                    vectors.append({
                        "case": f"{student}:{tid}:ai_only",
                        "student": student,
                        "terminal_id": tid,
                        "overlay": {},
                        "checks": [{"check_id": c["check_id"], "kind": c["kind"],
                                    "points": c["points"], "tariff": c.get("tariff"),
                                    "partial_fraction": c["partial_fraction"],
                                    "verdict": c["verdict"],
                                    "quote_status": c.get("quote_status")}
                                   for c in (leaf.get("checks") or [])],
                        "expected_points_awarded": leaf["points_awarded"],
                        "points_possible": leaf["points_possible"],
                    })
    return vectors


def _synthetic_edge_cases(drafts: dict) -> dict:
    """The three shapes this cohort cannot produce, derived from a real draft.

    `skipped_no_answer` in particular can NEVER come from these fixtures: it
    needs a scope with no student answer, and all five pilot students answered
    every question. (Spec §1.7 names din Q2.ב for it, but din answered Q2.ב —
    her scan was read during the PL-9 work. That is a spec bug.)

    Every object here carries `"_synthetic": true` and a reason, so it cannot be
    mistaken for observed output if a copy ever escapes.
    """
    import copy
    base = copy.deepcopy(drafts["dan_basiuk"])
    base["_synthetic"] = True
    base["_synthetic_reason"] = (
        "Derived from a real dan_basiuk draft. Carries the three review-surface "
        "states this cohort cannot produce: not_found and fuzzy quote validation, "
        "and a skipped_no_answer scope."
    )

    touched = {"not_found": None, "fuzzy": None, "skipped": None}
    for scope in base.get("scope_outcomes") or []:
        for crit in scope.get("criterion_outcomes") or []:
            for leaf in (crit.get("sub_criterion_outcomes") or [crit]):
                for ch in (leaf.get("checks") or []):
                    if ch.get("quote_status") != "exact":
                        continue
                    if touched["not_found"] is None:
                        # a MET claim whose span does not appear in the answer —
                        # the invented-credit case the look-count exists to catch
                        ch["quote_status"] = "not_found"
                        ch["_synthetic"] = True
                        touched["not_found"] = ch["check_id"]
                    elif touched["fuzzy"] is None:
                        ch["quote_status"] = "fuzzy"
                        ch["_synthetic"] = True
                        touched["fuzzy"] = ch["check_id"]

    # a scope the student left unanswered: no verdicts, no checks, zero points
    if base.get("scope_outcomes"):
        sk = copy.deepcopy(base["scope_outcomes"][-1])
        sk["graded_by"] = "skipped_no_answer"
        sk["points_awarded"] = "0"
        sk["_synthetic"] = True
        for crit in sk.get("criterion_outcomes") or []:
            for leaf in (crit.get("sub_criterion_outcomes") or [crit]):
                leaf["checks"] = None
                leaf["points_awarded"] = "0"
            crit["points_awarded"] = "0"
        base["scope_outcomes"].append(sk)
        touched["skipped"] = sk.get("question_id")

    base["_synthetic_touched"] = touched
    return base


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--from-run", required=True,
                    help="eval results dir holding drafts/ (generated with the pin ON)")
    ap.add_argument("--with-synthetic", action="store_true",
                    help="also emit the three shapes this cohort cannot produce "
                         "(deleted again after the tests run — owner instruction)")
    ap.add_argument("--check", action="store_true",
                    help="regenerate and fail on any diff (fixtures-regenerate-clean)")
    args = ap.parse_args()

    run_dir = Path(args.from_run)
    if not run_dir.is_absolute():
        run_dir = BACKEND / run_dir
    drafts = _load_drafts(run_dir)
    cov = _coverage(drafts)

    if cov["terminals_with_checks"] == 0:
        raise SystemExit(
            f"run {run_dir.name} carries NO checks[] — it predates PR-G1, so it "
            f"cannot seed the fixture set. Re-run the eval with the v5 pin.")

    files = {f"draft_{s}.json": d for s, d in drafts.items()}
    files["pricing_vectors.json"] = _pricing_vectors(drafts)
    if args.with_synthetic:
        files["draft_SYNTHETIC_edge_cases.json"] = _synthetic_edge_cases(drafts)

    files["MANIFEST.json"] = {
        "generated_from_run": run_dir.name,
        "generator": "scripts/gen_grade_review_fixtures.py",
        "provenance": {k: drafts[STUDENTS[0]].get(k)
                       for k in ("model_version", "prompt_version", "plan_version")},
        "coverage": cov,
        "pending": {
            "overlay_examples.json": "PR-G5 — needs the verdict-level overlay model",
            "pricing_vectors.json:overlay_cases": "PR-G5 — AI-only vectors present now",
            "batch_feed_*.json": "PR-G8 — the batch feed shape does not exist yet",
            "audit_deltas_example.json": "STRUCK by ruling R-1 (audit deferred)",
        },
        "coverage_gap": {
            "not_found": "absent — this run quoted exactly on all 336 verified spans",
            "fuzzy": "absent — same",
            "skipped_no_answer": "UNOBTAINABLE from this cohort: all five students "
                                 "answered every question. Spec §1.7 names din Q2.ב, "
                                 "but din answered Q2.ב — that is a spec bug.",
            "how_covered": "synthetic shapes via --with-synthetic; generated for the "
                           "test run and deleted afterwards so the published set "
                           "stays observed-only (owner instruction)",
        },
    }

    OUT.mkdir(parents=True, exist_ok=True)
    changed = []
    for name, payload in files.items():
        text = json.dumps(payload, ensure_ascii=False, indent=1, sort_keys=True) + "\n"
        path = OUT / name
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            changed.append(name)
            if not args.check:
                path.write_text(text, encoding="utf-8", newline="\n")

    if args.check and changed:
        raise SystemExit(f"fixtures are stale, regenerate: {changed}")
    print(f"{'unchanged' if not changed else 'wrote'}: {len(files)} file(s) -> {OUT}")
    print(f"coverage: checks on {cov['terminals_with_checks']} terminal(s), "
          f"{len(cov['not_found'])} not_found, {len(cov['fuzzy'])} fuzzy, "
          f"{len(cov['skipped_no_answer'])} skipped scope(s), "
          f"{len(cov['failed_scope'])} failed scope(s)")


if __name__ == "__main__":
    main()
