"""
Generate migration 032 from a FRESH read of a live database's FK graph.

    python scripts/gen_migration_032.py --database-url URL            # print it
    python scripts/gen_migration_032.py --database-url URL --write    # write migrations/032_*.sql
    python scripts/gen_migration_032.py --database-url URL --check    # the deploy gate

WHY A GENERATOR (docs/PURGE_CENSUS.md §20, ruled 2026-09-23). Postgres cannot
change an FK's ON DELETE action in place, so 032 drops and re-creates every FK
out of the five student-data tables under its existing name. The census table
is a snapshot; production is the truth. So the SQL is written from what the
database actually holds (`pg_get_constraintdef`), with only the ON DELETE clause
removed — everything else each constraint carries (columns, target, ON UPDATE,
MATCH, DEFERRABLE) survives byte for byte.

`--check` is the deploy-time gate: regenerate from production and compare with
the committed file. Identical ⇒ apply it. Any difference ⇒ STOP: the schema
moved since the file was reviewed, and the difference is the review.

The output carries no timestamp and no database name, so two databases with the
same FK graph produce the same file — which is what makes `--check` meaningful.
Read-only: this script never writes to the database it reads.
"""
from __future__ import annotations

import argparse
import asyncio
import re
import sys
from pathlib import Path

import asyncpg

# AM-B1, keyed on the REFERENCING table.
FIVE = ("students", "transcriptions", "graded_tests", "graded_test_pdfs", "transcription_jobs")
DEFERRED = "graded_tests_regraded_to_id_fkey"       # extend_chain's insert order needs it

# AM-B4 — added by 032, excluded from the fresh read so a re-run reproduces the file.
TENANT_UNIQUES = (
    ("students", "students_id_user_id_key", "(id, user_id)"),
    ("transcriptions", "transcriptions_id_user_id_key", "(id, user_id)"),
)
TENANT_FKEYS = (
    ("transcriptions", "transcriptions_student_tenant_fkey",
     "FOREIGN KEY (student_id, user_id) REFERENCES public.students(id, user_id)"),
    ("graded_tests", "graded_tests_student_tenant_fkey",
     "FOREIGN KEY (student_id, user_id) REFERENCES public.students(id, user_id)"),
    ("graded_tests", "graded_tests_transcription_tenant_fkey",
     "FOREIGN KEY (transcription_id, user_id) REFERENCES public.transcriptions(id, user_id)"),
    ("transcription_jobs", "transcription_jobs_transcription_tenant_fkey",
     "FOREIGN KEY (transcription_id, user_id) REFERENCES public.transcriptions(id, user_id)"),
)

ON_DELETE = re.compile(r" ON DELETE (?:CASCADE|SET NULL|SET DEFAULT|RESTRICT)(?: \([^)]*\))?")

MIGRATION = Path(__file__).resolve().parents[1] / "migrations" / "032_student_data_fks_no_action.sql"

HEADER = """\
-- 032 — every foreign key OUT OF the five student-data tables becomes
--       ON DELETE NO ACTION (AM-B1), and tenant consistency is enforced by the
--       database (AM-B4).
--
-- GENERATED by backend/scripts/gen_migration_032.py from a fresh read of the
-- live FK graph. Do not hand-edit: regenerate, and let `--check` compare it with
-- production immediately before it is applied (docs/PURGE_CENSUS.md §20).
--
-- WHY (PURGE_CENSUS §0, §1). `DELETE FROM students` succeeded, and the database
-- — not the code — decided what went with it: grades and approved scans by
-- CASCADE, jobs orphaned by SET NULL, every stored object left behind. A purge on
-- that graph would pass its own tests while PRV-6 (plan equals execution) was
-- false by construction. After 032 a delete out of these tables happens only
-- when it is spelled out; anything else fails loudly and deletes nothing (PRV-8).
--
-- HOW. Postgres cannot alter an FK's ON DELETE action in place, so each FK is
-- dropped and re-created under its EXISTING name, with only its ON DELETE clause
-- removed (NO ACTION is the default). `regraded_to_id` stays DEFERRABLE
-- INITIALLY DEFERRED — extend_chain's insert order depends on it. NO ACTION, not
-- RESTRICT: NO ACTION checks at statement end, so a whole revision chain still
-- deletes in one statement. class_memberships is outside the set and keeps its
-- cascades. One transaction: all of it, or none of it.
--
-- AM-B4. UNIQUE (id, user_id) on students and transcriptions, and four composite
-- *_tenant_fkey constraints, so no row can reference another teacher's student
-- or scan. The single-column FKs stay (the ORM's relationships use them).
-- Before applying: re-run census query D (zero violations), then pg_dump
-- production to db-archive/ — PITR is off, so that dump is the restore point.
--
-- Idempotent: every constraint is dropped IF EXISTS and re-added, tenant FKs
-- before the uniques they depend on.

BEGIN;
"""


async def read_fks(url: str) -> list[tuple[str, str, str]]:
    conn = await asyncpg.connect(re.sub(r"^postgresql\+asyncpg://", "postgresql://", url),
                                 statement_cache_size=0)
    try:
        # With public off the search_path, pg_get_constraintdef qualifies every
        # referenced table, so the file does not depend on the applier's path.
        await conn.execute("SET search_path = pg_catalog")
        rows = await conn.fetch("""
            SELECT rel.relname AS table_name, con.conname, pg_get_constraintdef(con.oid) AS def
              FROM pg_constraint con
              JOIN pg_class rel ON rel.oid = con.conrelid
              JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
             WHERE con.contype = 'f' AND nsp.nspname = 'public'
               AND rel.relname = ANY($1::text[]) AND NOT (con.conname = ANY($2::text[]))
             ORDER BY rel.relname, con.conname""",
            list(FIVE), [name for _, name, _ in TENANT_FKEYS])
    finally:
        await conn.close()
    return [(r["table_name"], r["conname"], r["def"]) for r in rows]


def render(fks: list[tuple[str, str, str]]) -> str:
    names = {name for _, name, _ in fks}
    if DEFERRED not in names:
        raise SystemExit(f"refusing: {DEFERRED} was not found — the graph is not what the census describes")
    out = [HEADER]
    out.append(f"-- AM-B1: {len(fks)} foreign keys, re-created without an ON DELETE action.\n")
    for table, name, definition in fks:
        new = ON_DELETE.sub("", definition)
        if name == DEFERRED and "DEFERRABLE INITIALLY DEFERRED" not in new:
            raise SystemExit(f"refusing: {name} is not DEFERRABLE INITIALLY DEFERRED on this database")
        out.append(f"ALTER TABLE public.{table} DROP CONSTRAINT IF EXISTS {name};\n"
                   f"ALTER TABLE public.{table} ADD CONSTRAINT {name} {new};\n")
    out.append("\n-- AM-B4: tenant consistency. Drop the composite FKs before the uniques they use.\n")
    for table, name, _ in TENANT_FKEYS:
        out.append(f"ALTER TABLE public.{table} DROP CONSTRAINT IF EXISTS {name};\n")
    for table, name, cols in TENANT_UNIQUES:
        out.append(f"ALTER TABLE public.{table} DROP CONSTRAINT IF EXISTS {name};\n"
                   f"ALTER TABLE public.{table} ADD CONSTRAINT {name} UNIQUE {cols};\n")
    for table, name, definition in TENANT_FKEYS:
        out.append(f"ALTER TABLE public.{table} ADD CONSTRAINT {name} {definition};\n")
    out.append("\n-- Commit token LAST: this row lands only if every statement above landed.\n"
               "INSERT INTO public.schema_migrations (version, note)\n"
               "VALUES ('032', 'student-data FKs -> ON DELETE NO ACTION (AM-B1) + tenant "
               "constraints (AM-B4): a delete happens only when it is spelled out')\n"
               "ON CONFLICT DO NOTHING;\n\nCOMMIT;\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--database-url", required=True)
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = ap.parse_args()

    sql = render(asyncio.run(read_fks(args.database_url)))
    if args.write:
        MIGRATION.write_text(sql, encoding="utf-8", newline="\n")
        print(f"wrote {MIGRATION.name}")
    elif args.check:
        committed = MIGRATION.read_text(encoding="utf-8").replace("\r\n", "\n")
        if committed != sql:
            import difflib
            sys.stdout.writelines(difflib.unified_diff(
                committed.splitlines(True), sql.splitlines(True), "committed", "fresh read"))
            print("\nSTOP: a fresh read does not reproduce the committed 032.")
            return 1
        print("OK: a fresh read reproduces the committed 032 byte for byte.")
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
