/**
 * The §1.7 fixture set, as the frontend sees it.
 *
 * THE FIXTURES ARE NOT COPIED HERE. They live in
 * `backend/tests/fixtures/grade_review/`, are GENERATED by
 * `scripts/gen_grade_review_fixtures.py` from real grading runs, and are the
 * executable form of the wire contract. Copying them into `src/mocks/` would
 * fork ground truth (CLAUDE.md §0.4) and the copy would rot the first time a
 * shape changed — which is the whole failure the fixture seam exists to
 * prevent. Node reads them in place; the browser reads them through the
 * dev-only route handler in `src/app/api/dev-fixtures/`.
 *
 * WHAT THIS FILE IS: the manifest as TYPES — which fixtures exist, which are
 * pending and WHY. `registry.test.ts` set-compares it against the backend's own
 * MANIFEST.json, so the day PR-G5 or PR-G8 publishes a pending fixture, this
 * file fails rather than quietly continuing to serve a gap.
 *
 * WHAT A PENDING FIXTURE DOES: it refuses. It does not get a plausible payload
 * invented for it. A hand-written `batch_feed_landing.json` would let F1 build
 * a dashboard against a shape nobody has agreed to, and the disagreement would
 * surface at integration, in the most expensive place — that is exactly
 * "adapting to a backend gap", which §0 of the PR spec forbids.
 */

/** The five pilot students whose real drafts were published (PR-G1). */
export const FIXTURE_STUDENTS = [
    'dan_basiuk',
    'din_ezra',
    'moran_aharon',
    'omer_gelber',
    'yonatan_basiuk',
] as const;

export type FixtureStudent = (typeof FIXTURE_STUDENTS)[number];

/**
 * The four dashboard states (PR-G8, published 2026-08-31). Each pins something
 * the dashboard has to get right, and the order is the batch's own life:
 *
 *   landing   nothing has landed — the ETA is all she has
 *   running   carries a NULL look_count on purpose: the unparseable draft. No
 *             number, not a reassuring 0 — 0 reads as "nothing to check" on
 *             precisely the test that most needs her eye (§3.5a)
 *   done      opened but unfinished, ETA unknown → «עוד רגע», never a
 *             fabricated figure
 *   complete  a FAILED test still visible, so the batch completes with its
 *             hole showing rather than as 4 of 4
 */
export const BATCH_FEED_STATES = ['landing', 'running', 'done', 'complete'] as const;

export type BatchFeedState = (typeof BATCH_FEED_STATES)[number];

/**
 * The four students whose APPROVED contracts exist (F3).
 *
 * `din_ezra` is absent and its absence is a FINDING, not a gap: its draft
 * carries an unresolved `llm_failure` ERROR on q2.ב, so the real approval gate
 * refuses to compile it (§5 — an ERROR blocks approval). There is no honest
 * approved contract for that test until the teacher resolves the failed scope,
 * and inventing one would publish a returned exam for a grade nobody signed.
 * Generated by `scripts/gen_returned_exam_fixtures.py`, which runs the REAL
 * compiler over the REAL drafts and the rubric they were graded against.
 */
export const APPROVED_FIXTURE_STUDENTS = [
    'dan_basiuk',
    'moran_aharon',
    'omer_gelber',
    'yonatan_basiuk',
] as const

/** Files the backend has published, exactly as named on disk. */
export const PRESENT_FIXTURES: readonly string[] = [
    ...FIXTURE_STUDENTS.map((s) => `draft_${s}.json`),
    ...APPROVED_FIXTURE_STUDENTS.map((s) => `approved_${s}.json`),
    ...BATCH_FEED_STATES.map((s) => `batch_feed_${s}.json`),
    'draft_SYNTHETIC_edge_cases.json',
    'pricing_vectors.json',
    'MANIFEST.json',
];

/**
 * Files §1.7 names that do NOT exist yet, with the backend's own reason.
 * Mirrors `MANIFEST.json:pending` minus anything since published —
 * `registry.test.ts` proves both halves of that claim against disk.
 */
export const PENDING_FIXTURES: Readonly<Record<string, string>> = {
    'overlay_examples.json': 'PR-G5 — needs the verdict-level overlay model',
    'pricing_vectors.json:overlay_cases': 'PR-G5 — AI-only vectors present now',
    'audit_deltas_example.json': 'STRUCK by ruling R-1 (audit deferred)',
};

/**
 * Entries `MANIFEST.json` still calls pending that have since been PUBLISHED.
 *
 * The staleness is STRUCTURAL, not a missed regeneration: the `pending` dict is
 * a hardcoded literal in `gen_grade_review_fixtures.py`, and the batch feed is
 * written by a different script (`gen_batch_feed_fixtures.py`) that does not
 * touch it. Re-running the generator reproduces the stale claim byte for byte
 * — verified 2026-08-31. The fix is a one-line edit to that dict, backend-side.
 *
 * Recorded here rather than silently dropped, because a mirror that quietly
 * disagrees with the thing it mirrors is worse than no mirror.
 */
export const MANIFEST_STALE_PENDING: readonly string[] = ['batch_feed_*.json'];

/**
 * The three review-surface states this cohort could not produce, DERIVED from a
 * real dan_basiuk draft by the backend generator's `--with-synthetic` flag:
 * a `not_found` quote (the invented-credit case), a `fuzzy` one, and a
 * `skipped_no_answer` scope.
 *
 * Kept on disk by owner ruling (2026-08-31), superseding the earlier "generate
 * for the test run then delete" instruction — F2 cannot build the evidence
 * highlight against states that do not exist anywhere. Every object inside
 * carries `_synthetic: true` and a reason, so a stray copy can never be
 * mistaken for observed output, and it is named apart from the five real
 * drafts here for the same reason.
 */
export const SYNTHETIC_FIXTURE = 'draft_SYNTHETIC_edge_cases.json';

/**
 * Shapes §1.7 asks the set to CONTAIN that this cohort could not produce, with
 * the backend's finding. Kept because an F2 developer looking for the
 * `not_found` evidence case needs to know it is absent from the OBSERVED
 * drafts by observation, not by oversight — SYNTHETIC_FIXTURE below is where
 * all three now live.
 */
export const COVERAGE_GAPS: Readonly<Record<string, string>> = {
    not_found: 'absent — this run quoted exactly on all 336 verified spans',
    fuzzy: 'absent — same',
    skipped_no_answer:
        'UNOBTAINABLE from this cohort: all five students answered every ' +
        'question. Spec §1.7 names din Q2.ב, but din answered Q2.ב — that is ' +
        'a spec bug.',
};

export const FIXTURE_DIR_FROM_FRONTEND = '../backend/tests/fixtures/grade_review';

/** Dev route path for one fixture file. */
export function fixtureUrl(name: string): string {
    return `/api/dev-fixtures/grade_review/${name}`;
}

export class PendingFixtureError extends Error {
    constructor(readonly fixture: string, reason: string) {
        super(`fixture ${fixture} is not published: ${reason}`);
        this.name = 'PendingFixtureError';
    }
}

/** Throws with the backend's reason rather than inventing a payload. */
export function assertFixturePublished(name: string): void {
    if (PRESENT_FIXTURES.includes(name)) return;
    const pending = PENDING_FIXTURES[name]
        ?? Object.entries(PENDING_FIXTURES)
            .find(([key]) => key.endsWith('*.json') && name.startsWith(key.slice(0, -6)))?.[1];
    throw new PendingFixtureError(name, pending ?? 'not part of the §1.7 set');
}
