-- 032 — every foreign key OUT OF the five student-data tables becomes
--       ON DELETE NO ACTION (AM-B1), and tenant consistency is enforced by the
--       database (AM-B4).
--
-- GENERATED by backend/scripts/gen_migration_032.py from a fresh read of the
-- live FK graph. Do not hand-edit: regenerate, and let `--check` compare it with
-- production immediately before it is applied (docs/PURGE_CENSUS.md §20).
--
-- WHY (PURGE_CENSUS §0, §1). `DELETE FROM students` succeeded, and the database
-- — not the code — decided what went with it: grades and approved scans by
-- CASCADE, jobs orphaned by SET NULL, every stored object left behind. A purge on
-- that graph would pass its own tests while PRV-6 (plan equals execution) was
-- false by construction. After 032 a delete out of these tables happens only
-- when it is spelled out; anything else fails loudly and deletes nothing (PRV-8).
--
-- HOW. Postgres cannot alter an FK's ON DELETE action in place, so each FK is
-- dropped and re-created under its EXISTING name, with only its ON DELETE clause
-- removed (NO ACTION is the default). `regraded_to_id` stays DEFERRABLE
-- INITIALLY DEFERRED — extend_chain's insert order depends on it. NO ACTION, not
-- RESTRICT: NO ACTION checks at statement end, so a whole revision chain still
-- deletes in one statement. class_memberships is outside the set and keeps its
-- cascades. One transaction: all of it, or none of it.
--
-- AM-B4. UNIQUE (id, user_id) on students and transcriptions, and four composite
-- *_tenant_fkey constraints, so no row can reference another teacher's student
-- or scan. The single-column FKs stay (the ORM's relationships use them).
-- Before applying: re-run census query D (zero violations), then pg_dump
-- production to db-archive/ — PITR is off, so that dump is the restore point.
--
-- Idempotent: every constraint is dropped IF EXISTS and re-added, tenant FKs
-- before the uniques they depend on.

BEGIN;
-- AM-B1: 18 foreign keys, re-created without an ON DELETE action.
ALTER TABLE public.graded_test_pdfs DROP CONSTRAINT IF EXISTS graded_test_pdfs_graded_test_id_fkey;
ALTER TABLE public.graded_test_pdfs ADD CONSTRAINT graded_test_pdfs_graded_test_id_fkey FOREIGN KEY (graded_test_id) REFERENCES public.graded_tests(id);
ALTER TABLE public.graded_test_pdfs DROP CONSTRAINT IF EXISTS graded_test_pdfs_rubric_id_fkey;
ALTER TABLE public.graded_test_pdfs ADD CONSTRAINT graded_test_pdfs_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.rubrics(id);
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_batch_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.grading_batches(id);
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_regraded_from_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_regraded_from_id_fkey FOREIGN KEY (regraded_from_id) REFERENCES public.graded_tests(id);
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_regraded_to_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_regraded_to_id_fkey FOREIGN KEY (regraded_to_id) REFERENCES public.graded_tests(id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_rubric_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.rubrics(id);
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_student_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_transcription_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_transcription_id_fkey FOREIGN KEY (transcription_id) REFERENCES public.transcriptions(id);
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_user_id_fkey;
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_user_id_fkey;
ALTER TABLE public.students ADD CONSTRAINT students_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.transcription_jobs DROP CONSTRAINT IF EXISTS transcription_jobs_batch_id_fkey;
ALTER TABLE public.transcription_jobs ADD CONSTRAINT transcription_jobs_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.grading_batches(id);
ALTER TABLE public.transcription_jobs DROP CONSTRAINT IF EXISTS transcription_jobs_rubric_id_fkey;
ALTER TABLE public.transcription_jobs ADD CONSTRAINT transcription_jobs_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.rubrics(id);
ALTER TABLE public.transcription_jobs DROP CONSTRAINT IF EXISTS transcription_jobs_transcription_id_fkey;
ALTER TABLE public.transcription_jobs ADD CONSTRAINT transcription_jobs_transcription_id_fkey FOREIGN KEY (transcription_id) REFERENCES public.transcriptions(id);
ALTER TABLE public.transcription_jobs DROP CONSTRAINT IF EXISTS transcription_jobs_user_id_fkey;
ALTER TABLE public.transcription_jobs ADD CONSTRAINT transcription_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE public.transcriptions DROP CONSTRAINT IF EXISTS transcriptions_batch_id_fkey;
ALTER TABLE public.transcriptions ADD CONSTRAINT transcriptions_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.grading_batches(id);
ALTER TABLE public.transcriptions DROP CONSTRAINT IF EXISTS transcriptions_rubric_id_fkey;
ALTER TABLE public.transcriptions ADD CONSTRAINT transcriptions_rubric_id_fkey FOREIGN KEY (rubric_id) REFERENCES public.rubrics(id);
ALTER TABLE public.transcriptions DROP CONSTRAINT IF EXISTS transcriptions_student_id_fkey;
ALTER TABLE public.transcriptions ADD CONSTRAINT transcriptions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id);
ALTER TABLE public.transcriptions DROP CONSTRAINT IF EXISTS transcriptions_user_id_fkey;
ALTER TABLE public.transcriptions ADD CONSTRAINT transcriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);

-- AM-B4: tenant consistency. Drop the composite FKs before the uniques they use.
ALTER TABLE public.transcriptions DROP CONSTRAINT IF EXISTS transcriptions_student_tenant_fkey;
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_student_tenant_fkey;
ALTER TABLE public.graded_tests DROP CONSTRAINT IF EXISTS graded_tests_transcription_tenant_fkey;
ALTER TABLE public.transcription_jobs DROP CONSTRAINT IF EXISTS transcription_jobs_transcription_tenant_fkey;
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_id_user_id_key;
ALTER TABLE public.students ADD CONSTRAINT students_id_user_id_key UNIQUE (id, user_id);
ALTER TABLE public.transcriptions DROP CONSTRAINT IF EXISTS transcriptions_id_user_id_key;
ALTER TABLE public.transcriptions ADD CONSTRAINT transcriptions_id_user_id_key UNIQUE (id, user_id);
ALTER TABLE public.transcriptions ADD CONSTRAINT transcriptions_student_tenant_fkey FOREIGN KEY (student_id, user_id) REFERENCES public.students(id, user_id);
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_student_tenant_fkey FOREIGN KEY (student_id, user_id) REFERENCES public.students(id, user_id);
ALTER TABLE public.graded_tests ADD CONSTRAINT graded_tests_transcription_tenant_fkey FOREIGN KEY (transcription_id, user_id) REFERENCES public.transcriptions(id, user_id);
ALTER TABLE public.transcription_jobs ADD CONSTRAINT transcription_jobs_transcription_tenant_fkey FOREIGN KEY (transcription_id, user_id) REFERENCES public.transcriptions(id, user_id);

-- Commit token LAST: this row lands only if every statement above landed.
INSERT INTO public.schema_migrations (version, note)
VALUES ('032', 'student-data FKs -> ON DELETE NO ACTION (AM-B1) + tenant constraints (AM-B4): a delete happens only when it is spelled out')
ON CONFLICT DO NOTHING;

COMMIT;
