"""
PR-G1(e) — the §1.7 fixture set is the seam's executable form.

These pin the fixtures the frontend builds F0 against: they must parse as real
`GradedTestDraft`s, carry the per-check record, and price consistently with the
Python pricer (the TS mirror then has to reproduce `pricing_vectors.json`
byte-for-byte).

The synthetic edge-case draft is deliberately EPHEMERAL (owner instruction): it
is generated for a test run and deleted so the published set stays observed-only.
Its test therefore SKIPS when the file is absent — a fixture that must not be
committed cannot be a hard dependency of the suite.
"""
import json
from decimal import Decimal
from pathlib import Path

import pytest

from app.schemas.graded_test_draft import GradedTestDraft

FIX = Path(__file__).resolve().parent / "grade_review"
SYNTHETIC = FIX / "draft_SYNTHETIC_edge_cases.json"
STUDENTS = ("dan_basiuk", "din_ezra", "moran_aharon", "omer_gelber", "yonatan_basiuk")


def _load(name: str) -> dict:
    return json.loads((FIX / name).read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# fixtures-regenerate-clean
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("student", STUDENTS)
def test_fixture_drafts_are_real_parseable_drafts(student):
    """Generated by real code paths, so they must round-trip through the real
    type — a hand-edited fixture would fail here."""
    draft = GradedTestDraft.model_validate(_load(f"draft_{student}.json"))
    assert draft.plan_version, "a v5 fixture must carry its plan pin"
    assert draft.model_version and draft.prompt_version


def test_every_graded_terminal_carries_checks():
    """The whole point of PR-G1: the review module renders checks and nothing
    else, so a graded terminal without them would render an empty card."""
    for student in STUDENTS:
        draft = GradedTestDraft.model_validate(_load(f"draft_{student}.json"))
        for scope in draft.scope_outcomes:
            if scope.graded_by != "llm":
                continue
            for crit in scope.criterion_outcomes:
                for leaf in (crit.sub_criterion_outcomes or [crit]):
                    tid = getattr(leaf, "sub_criterion_id", None) or crit.criterion_id
                    assert leaf.checks, f"{student}:{tid} has no checks"


def test_pricing_vectors_match_the_drafts_they_came_from():
    """`pricing_vectors.json` is what the frontend's TS mirror must reproduce.
    If a vector drifts from its own draft, the mirror would be validated against
    a number the backend never produced."""
    vectors = _load("pricing_vectors.json")
    assert vectors, "no vectors emitted"

    awarded = {}
    for student in STUDENTS:
        draft = GradedTestDraft.model_validate(_load(f"draft_{student}.json"))
        for scope in draft.scope_outcomes:
            for crit in scope.criterion_outcomes:
                for leaf in (crit.sub_criterion_outcomes or [crit]):
                    tid = getattr(leaf, "sub_criterion_id", None) or crit.criterion_id
                    awarded[(student, tid)] = leaf.points_awarded

    for v in vectors:
        key = (v["student"], v["terminal_id"])
        assert key in awarded, f"vector for unknown terminal {key}"
        assert Decimal(v["expected_points_awarded"]) == awarded[key], (
            f"{key}: vector says {v['expected_points_awarded']}, "
            f"draft says {awarded[key]}")


def test_manifest_states_provenance_and_the_coverage_gap():
    """A fixture set that quietly lacks an edge case stops testing the thing it
    exists to test. The manifest has to say so out loud."""
    m = _load("MANIFEST.json")
    assert m["generated_from_run"]
    assert m["provenance"]["plan_version"]
    assert "skipped_no_answer" in m["coverage_gap"]
    assert m["pending"]["audit_deltas_example.json"].startswith("STRUCK")


# ---------------------------------------------------------------------------
# the synthetic edge cases — ephemeral by instruction
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not SYNTHETIC.exists(),
                    reason="synthetic edge cases are generated for a test run and "
                           "deleted afterwards so the published set stays observed-only")
def test_synthetic_draft_carries_the_three_missing_review_states():
    """This cohort produced no not_found, no fuzzy, and no skipped scope: sonnet
    quoted exactly on all 336 verified spans, and all five students answered
    every question. Those are review-surface states the frontend must render, so
    they are derived from a real draft and clearly labelled."""
    raw = _load(SYNTHETIC.name)
    assert raw["_synthetic"] is True and raw["_synthetic_reason"]

    statuses, skipped = set(), []
    for scope in raw["scope_outcomes"]:
        if scope.get("graded_by") == "skipped_no_answer":
            skipped.append(scope.get("question_id"))
        for crit in scope.get("criterion_outcomes") or []:
            for leaf in (crit.get("sub_criterion_outcomes") or [crit]):
                for ch in (leaf.get("checks") or []):
                    statuses.add(ch.get("quote_status"))

    assert "not_found" in statuses, "the invented-credit state is missing"
    assert "fuzzy" in statuses
    assert skipped, "no skipped_no_answer scope"

    # and it must still be a valid draft — a synthetic fixture that does not
    # parse would test the frontend against a shape the backend cannot emit
    GradedTestDraft.model_validate(raw)
